import os
import subprocess
import sys

import numpy as np

# Train a small MLP value model on self-play states -> did the sampled seat win.
# Input CSV (from `prism_selfplay --dump`): label, f0..f25 (f0=1 bias). Output: a
# generated C++ header the bot's learned leaf reads. Features are set-agnostic
# aggregates (bot.cpp stateFeatures), so the model transfers across set changes.

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, "engine", "include", "prism", "value_weights.hpp")
H = 24  # hidden units


def main():
    csv = sys.argv[1] if len(sys.argv) > 1 else "value-data.csv"
    data = np.loadtxt(csv, delimiter=",")
    y = data[:, 0]
    X = data[:, 1:]  # includes bias column f0=1
    n, d = X.shape
    rng = np.random.default_rng(0)
    idx = rng.permutation(n)
    cut = int(0.85 * n)
    tr, va = idx[:cut], idx[cut:]
    Xtr, ytr, Xva, yva = X[tr], y[tr], X[va], y[va]

    W1 = rng.standard_normal((d, H)) * 0.1
    b1 = np.zeros(H)
    W2 = rng.standard_normal(H) * 0.1
    b2 = 0.0
    lr, lam = 0.2, 1e-5
    m = len(ytr)
    for _ in range(3000):
        A1 = np.tanh(Xtr @ W1 + b1)          # [m,H]
        p = 1.0 / (1.0 + np.exp(-(A1 @ W2 + b2)))
        dz2 = (p - ytr) / m                   # [m]
        dW2 = A1.T @ dz2 + lam * W2
        db2 = dz2.sum()
        dZ1 = np.outer(dz2, W2) * (1 - A1 * A1)  # [m,H]
        dW1 = Xtr.T @ dZ1 + lam * W1
        db1 = dZ1.sum(0)
        W1 -= lr * dW1
        b1 -= lr * db1
        W2 -= lr * dW2
        b2 -= lr * db2

    def acc(Xs, ys):
        A1 = np.tanh(Xs @ W1 + b1)
        p = 1.0 / (1.0 + np.exp(-(A1 @ W2 + b2)))
        return float(((p > 0.5) == ys).mean())

    base = max(yva.mean(), 1 - yva.mean())
    print(f"samples={n} feats={d} hidden={H}  win-rate={y.mean():.3f}")
    print(f"train acc={acc(Xtr, ytr):.3f}  val acc={acc(Xva, yva):.3f}  "
          f"(majority baseline {base:.3f})")

    def arr(a):
        return ", ".join("%+.6f" % x for x in a)

    with open(HEADER, "w") as f:
        f.write("#pragma once\n")
        f.write("// Generated by tools/train_value.py -- do not edit by hand.\n")
        f.write("// 1-hidden-layer tanh MLP over stateFeatures(); value in [-1,1].\n\n")
        f.write("namespace prism {\n\n")
        f.write(f"inline constexpr int kValueFeatureCount = {d};\n")
        f.write(f"inline constexpr int kValueHidden = {H};\n\n")
        f.write(f"inline constexpr double kValueW1[{d}][{H}] = {{\n")
        for i in range(d):
            f.write("    {" + arr(W1[i]) + "},\n")
        f.write("};\n")
        f.write(f"inline constexpr double kValueB1[{H}] = {{{arr(b1)}}};\n")
        f.write(f"inline constexpr double kValueW2[{H}] = {{{arr(W2)}}};\n")
        f.write("inline constexpr double kValueB2 = %+.6f;\n\n" % b2)
        f.write("}  // namespace prism\n")
    subprocess.run(["clang-format", "-i", HEADER], check=False)
    print("wrote", HEADER)


if __name__ == "__main__":
    main()
